// import './instance/index.js'
// import './lifecycle/index'
// import './bindData/index'
// import './computed/index'
// import './directive/index'
// import './component/index'
// import './extend/index'
// import './v-model/index'
import './advance-last/index'
